config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registration'}
  get 'countries/index'
  root 'countries#index'


  #get 'delers/index'
 # get 'delers/new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #resources :users 
  resources :products
  resources :countries
  resources :product_types
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :product_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [ :owner, :delar ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :mobile])
      #devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :terms, :location])
    end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @countries = Country.all
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(country_params)
      if @country.save
        redirect_to countries_path
      else
        render :new
      end
  end
  def edit
    @country = Country.find(params[:id])
  end

  def update
    @country = Country.find(params[:id])
      if @country.update(country_params)
        redirect_to countries_path
      else
        render :edit
      end
  end

  def destroy
    @country = Country.find(params[:id])
      if @country.destroy
        redirect_to countries_path
      else
        render :new
      end

  end



  private

  def country_params
    params.require(:country).permit(:name)
  end
end

app/controllers/delers_controller.rb
class DelersController < ApplicationController
  def index
  end

  def new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all

  end

  def new
    @product = Product.new
    #@user = User.find(params[:user])
  end

  def create
    @user = User.find(params[:product][:user_id])
    @product = Product.new(product_params)
      if @product.save
        redirect_to products_path
      else
        render :new
      end 
  end
  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
     if @product.destroy
      redirect_to products_path
    else
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(:product_name, :product_type, :product_price, :user_id, :role, :country_id, :product_type_id)
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to @user
      else
        render :new
      end
  end

   def edit
    @user = User.find(params[:id])
   end

   def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to users_path
      else
        render :edit
      end
   end
   def show 
    #@user = current_user.User.find(params[:id])
    #@user.find(current_user)
    @user = User.find(params[:id])
   end

   def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to users_path
    else
      render :new
   end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :role, :mobile, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/countries/edit.html.erb
<center><div class="card" style="width: 40rem;">
  <div class="card-header">
   <h3>Create Country</h3>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
   <%= form_with model: @country, class: "form-horizontal" do |form| %>
  <div class="row mb-3">
    <label for="inputEmail3" class="col-sm-2 col-form-label"> Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name,:required => true, class: "form-control", placeholder:"Enter Country Name" %>
    </div>
  </div>
  
  <button type="submit" class="btn btn-primary">Create</button>
</form>
</li>
<% end %>
   
  </ul>
</div></center>

app/views/countries/index.html.erb
<center><%= link_to "Add New Country", new_country_path, class:"btn btn-outline-primary"%></center>

<br><br>
<div class="container">
	<table class="table">
    <thead>
      <tr>
     	 <th>Country Name</th>
     	 <th>Actions</th>
     	</tr>
    </thead>
    <tbody>
    	<% @countries.each do |country|%>
      	<tr>
        	<td><%= link_to country.name %></td>
        	<td><%= link_to "edit", edit_country_path(country), class:"btn btn-outline-dark" %>
      		<%= link_to "delete", country_path(country), method: :delete, class: "btn btn-outline-danger" %></td>
				 </tr>  
			<% end %></td>    
 	  </tbody>
  </table>
</div>

app/views/countries/new.html.erb
<center><div class="card" style="width: 40rem;">
  <div class="card-header">
   <h3>Create Country</h3>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
   <%= form_with model: @country, class: "form-horizontal" do |form| %>
  <div class="row mb-3">
    <label for="inputEmail3" class="col-sm-2 col-form-label"> Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name,:required => true, class: "form-control", placeholder:"Enter Country Name" %>
    </div>
  </div>
  
  <button type="submit" class="btn btn-primary">Create</button>
</form>
</li>
<% end %>
   
  </ul>
</div></center>

app/views/delers/index.html.erb
<h1>Delers#index</h1>
<p>Find me in app/views/delers/index.html.erb</p>

app/views/delers/new.html.erb
<h1>Delers#new</h1>
<p>Find me in app/views/delers/new.html.erb</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
       <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%= link_to "Products", new_product_path, class: "nav-link" %>
      </li>
      <li class="nav-item ">
        <%#= link_to "Delars", new_user_path, class: "nav-link" %>
      </li>
      <!-- <li class="nav-item ">
        <%#= link_to "product listing", products_path, class: "nav-link" %>
      </li> -->
      <li class="nav-item ">
        <%= link_to "Countries", countries_path, class: "nav-link" %>
      </li>
     <!--  <li class="nav-item">
        <%#= link_to "Products",new_product_type_path, class: "nav-link" %>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav><br><br>

<!-- <nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <div class="text-right"> 
     <%#= link_to "Add new product" ,class:"btn btn-outline-primary"%>
    <%#= link_to "add new delar", new_user_path, class:"btn btn-outline-primary"%>
      <%#= link_to "product listing", products_path ,class:"btn btn-outline-primary"%>
      <%#= link_to "Add Country", countries_path ,class:"btn btn-outline-primary"%>
      <%#= link_to "Add Product Type",new_product_type_path, class: "btn btn-outline-primary" %>
  </div>
  </form>
</nav> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>User</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <ul>
      <% if user_signed_in? %>
        <h2>Log in</h2>
        <%= render "devise/shared/links" %>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Sign Up', new_user_registration_path %></li>
         <li> <%= link_to 'Log out', destroy_user_session_path, method: :delete  %></li>
      <% end %>
    </ul> 
    <%= render 'layouts/navigation' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/product_types/edit.html.erb
<center><div class="card" style="width: 40rem;">
  <div class="card-header">
   <h3>Create Product Type</h3>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= form_with model: @product_type, class: "form-horizontal" do |form| %>
        <div class="row mb-3">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <%= form.text_field :name,:required => true, class: "form-control", placeholder:"Enter Product Name" %>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
     <% end %>
    </li>
  </ul>
</div></center>

app/views/product_types/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th> Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @product_types.each do |product_type|%>
        <tr>
          <td><%= product_type.name %></td>
          <td><%= link_to "edit", edit_product_type_path(product_type), class:"btn btn-outline-dark" %>
          <%= link_to "delete", product_type_path(product_type), method: :delete , class:"btn btn-outline-danger"%></td>
        </tr>  
      <% end %>   
  </tbody>
  </table>
</div>
<center><h2><%= link_to "back", users_path, class:"btn btn-outline-info" %>
<%#= link_to "Add new product", new_product_path(:user), class:"btn btn-outline-success" %></h2></center>

app/views/product_types/new.html.erb
<center><div class="card" style="width: 40rem;">
  <div class="card-header">
   <h3>Create Product Type</h3>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= form_with model: @product_type, class: "form-horizontal" do |form| %>
        <div class="row mb-3">
          <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
          <div class="col-sm-10">
            <%= form.text_field :name,:required => true, class: "form-control", placeholder:"Enter Product Name" %>
          </div>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
     <% end %>
    </li>
  </ul>
</div></center>

app/views/products/edit.html.erb
<%= form_with model: @product, class: "form-horizontal" do |form| %>
 <%#= form.hidden_field :user_id, value: @user.id %>

 <b><div class="form-group">
    <label class="control-label col-sm-2" for="email">Product Name:</label>
    <div class="col-sm-6">
      <%= form.text_field :product_name, class: "form-control", placeholder:"Enter Product Name" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="pwd">Delar Name:</label>
    <div class="col-sm-10">
      <%= select_tag "User", options_from_collection_for_select(User.delar, :id, :name), { :prompt => 'Selected delar'}  %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Product Type</label>
    <div class="col-sm-6">
      <%= form.text_field :product_type, class: "form-control", placeholder:"Enter Product Type" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Product price:</label>
    <div class="col-sm-6">
      <%= form.text_field :product_price, class: "form-control", placeholder:"Enter Price" %>
    </div>
  </div>
 
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-danger">Submit</button>
    </div>
  </div></b>
<% end %>

app/views/products/index.html.erb
<div class="container">
	<table class="table">
    <thead>
      <tr>
      	<th>Product Id</th>
        <th>Product Name</th>
        <th>Product Price</th>
        <th>Actions</th>
        
      </tr>
    </thead>
    <tbody>
    	<% @products.each do |product|%>
      <tr>
      	<td><%= product.id %></td>
        <td><%= product.product_name %></td>
        <td><%= product.product_price %></td>
        <td><%= link_to "show", product_path(product) %></td>
        <td><h3><%#= link_to "+", new_product_path(:user) %></h3></td>
        <td><h2><%= link_to "-", product_path(product), method: :delete %></h2></td>
      <% end %></td>
    </tr>      
  </tbody>
  </table>
</div>

<center><h2><%= link_to "back", users_path, class:"btn btn-outline-info" %>
<%= link_to "Add new product", new_product_path(:user), class:"btn btn-outline-success" %></h2></center>

app/views/products/new.html.erb
<center><div class="card" style="width: 40rem;">
  <div class="card-header">
   <h3>Create Product</h3>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
    <%= form_with model: @product, class: "form-horizontal" do |form| %>
  <div class="row mb-3">
    <label for="inputEmail3" class="col-sm-2 col-form-label">Name</label>
    <div class="col-sm-10">
      <%= form.text_field :product_name,:required => true, class: "form-control", placeholder:"Enter Product Name" %>
    </div>
  </div>
  <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Owner Name</label>
    <div class="col-sm-10">
     <%= form.select "user_id", options_from_collection_for_select(User.owner, :id, :name), { :prompt => 'Selected Owner'}, class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Country</label>
    <div class="col-sm-10">
      <%= form.collection_select "country_id", Country.order(:name),:id,:name, {:prompt =>'select country origin '}, class:"form-control" %>
    </div>
  </div>
  <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Product Type</label>
    <div class="col-sm-10">
      <%= form.collection_select "product_type_id", ProductType.order(:name),:id,:name, {:prompt =>'select poduct type'}, class:"form-control" %>
    </div>
  </div>
   <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Price</label>
    <div class="col-sm-10">
     <%= form.text_field :product_price, :required => true,class: "form-control", placeholder:"Enter Price" %>
    </div>
  </div><br><br>

  <button type="submit" class="btn btn-primary">Create</button>
</form>
</li>
<% end %>
   
  </ul>
</div></center>

app/views/products/show.html.erb
	<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><ul><b>Product Detail</b></ul></h5>
    <p class="card-text"> Product Name:<%= @product.product_name %>  </p>
    <p class="card-text">Product Type:<%= @product.product_type %></p>
    <p class="card-text">Product Price:<%= @product.product_price %></p>
    <%= link_to "back", products_path , class: "btn btn-primary" %>
  </div>
</div>

app/views/users/edit.html.erb
<%= form_with model: @user, class: "form-horizontal" do |form| %>
 <b><div class="form-group">
    <label class="control-label col-sm-2" for="email">Name:</label>
    <div class="col-sm-6">
      <%= form.text_field :name, class: "form-control", placeholder:"Enter Name" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="pwd">Role:</label>
    <div class="col-sm-10">
      <%= form.select :role, User.roles.keys.map {|key| [t("user.#{key}"), key]} %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Mobile</label>
    <div class="col-sm-6">
      <%= form.text_field :mobile, class: "form-control", placeholder:"Enter Mobile" %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2" for="email">Email:</label>
    <div class="col-sm-6">
      <%= form.text_field :email, class: "form-control", placeholder:"Enter email" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label><input type="checkbox"> Remember me</label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-danger">Submit</button>
    </div>
  </div></b>
<% end %>

app/views/users/index.html.erb
<center><h2><button type="button" class="btn btn-outline-primary"><%= link_to "new user", new_user_path %></button></center>
<div class="container">
	<table class="table">
    <thead>
      <tr>
      	<th>Id</th>
        <th>User Name</th>
        <th>Role</th>
        <th>Mobile</th>
        <th>Email</th>
        <th>Actions</th> 
      </tr>
    </thead>
    <tbody>
    	<% @users.each do |user|%>
      <tr>
      	<td><%= user.id %></td>
        <td><%= link_to user.name ,user_path(user) %></td>
        <td><%= user.role %></td>
        <td><%= user.mobile %></td>
        <td><%= user.email %></td>
        <td><%= link_to "edit", edit_user_path(user), class:"btn btn-outline-dark" %>
            <%= link_to "delete", user_path(user), method: :delete, class: "btn btn-outline-danger" %>
        </td>
        <!-- <td><%# if user.owner? %>
          <%#= link_to "add new delar", new_user_path %>
        <%# else %>
          <%#= link_to "show product detail", products_path %>
          <%# end %>
        <td><%# if user.owner? %>
          <%#= link_to "add new product", new_product_path(user: user.id) %>
          <%# else %>
          <%#= link_to "my products", products_path %>
          <%#end %>
        </td> -->

      <% end %></td>
    </tr>      
  </tbody>
  </table>
</div>

app/views/users/new.html.erb
<center><div class="card" style="width: 40rem;">
  <div class="card-header">
   <h3>Create User</h3>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
   <%= form_with model: @user, class: "form-horizontal" do |form| %>
  <div class="row mb-3">
    <label for="inputEmail3" class="col-sm-2 col-form-label"> Name</label>
    <div class="col-sm-10">
      <%= form.text_field :name,:required => true, class: "form-control", placeholder:"Enter Name" %>
    </div>
  </div>
  <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Role</label>
    <div class="col-sm-10">
  
   <%= form.select "user_id", User.roles.keys.map {|key| [t("user.#{key}"), key]}, { :prompt => 'Select option'}, class: "form-control" %>
    </div>
  </div>
  <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label">Mobile</label>
    <div class="col-sm-10">
     <%= form.text_field :mobile, class: "form-control", placeholder:"Enter Mobile" %>
    </div>
  </div>
   <div class="row mb-3">
    <label for="inputPassword3" class="col-sm-2 col-form-label"> Email</label>
    <div class="col-sm-10">
    <%= form.text_field :email, class: "form-control", placeholder:"Enter email" %>
    </div>
  </div><br><br>

  <button type="submit" class="btn btn-primary">Create</button>
</form>
</li>
<% end %>
   
  </ul>
</div></center>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
	<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><ul><b>User Detail</b></ul></h5>
    <p class="card-text">  Name:<%= @user.name %>  </p>
     <p class="card-text"> Role:<%= @user.role %>  </p>
    <p class="card-text">Mobile:<%= @user.mobile %>  </p>
     <p class="card-text">Email:<%= @user.email %>  </p>
    <%= link_to "back", users_path , class: "btn btn-primary" %>
  </div>
</div>